# Generated by Django 2.1.5 on 2020-09-17 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20181028_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_id', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Unique ID for this particular project', null=True)),
                ('key_phrases', models.CharField(max_length=16384)),
                ('created_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
