# Generated by Django 2.1.5 on 2020-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='Created', max_length=200),
            preserve_default=False,
        ),
    ]
