# Generated by Django 2.1.5 on 2020-09-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_completion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
