# Generated by Django 2.1.5 on 2020-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_project_project_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_counts',
            field=models.CharField(default='0 out of 0', max_length=200),
        ),
    ]
